# Generated by Django 5.1.3 on 2024-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('color_code', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_color_code', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
