# Generated by Django 5.1.3 on 2024-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='color_code',
            new_name='colorCode',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='text_color_code',
            new_name='textColorCode',
        ),
    ]
