# Generated by Django 5.1.3 on 2025-01-03 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_color_code_contacts_colorcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('User Story', 'User Story'), ('Testing', 'Testing'), ('Research', 'Research'), ('Other', 'Other'), ('Technical Task', 'Technical Task'), ('Infrastructure', 'Infrastructure'), ('Enhancement', 'Enhancement'), ('Feature Request', 'Feature Request'), ('Bug', 'Bug'), ('Documentation', 'Documentation'), ('Design', 'Design')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('board', models.CharField(choices=[('toDo', 'To Do'), ('inProgress', 'In Progress'), ('awaitFeedback', 'Await Feedback'), ('done', 'Done')], default='toDo', max_length=50)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('assigned_to', models.JSONField(default=list)),
                ('subtasks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_list', to='contacts.tasks')),
            ],
        ),
    ]
