# Generated by Django 5.1.3 on 2025-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_category_tasks_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks', to='contacts.contacts'),
        ),
    ]
