# Generated by Django 5.1.3 on 2025-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contacts_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subtasks',
            field=models.JSONField(default=dict),
        ),
    ]
