# Generated by Django 5.1.3 on 2025-01-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_tasks_subtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='title',
            new_name='titlee',
        ),
    ]
