# Generated by Django 5.1.3 on 2025-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_rename_titlee_tasks_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='initials',
            field=models.CharField(default='', max_length=2),
        ),
    ]
