# Generated by Django 5.1.3 on 2025-01-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contacts_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('User Story', 'User Story'), ('Testing', 'Testing'), ('Research', 'Research'), ('Other', 'Other'), ('Technical Task', 'Technical Task'), ('Infrastructure', 'Infrastructure'), ('Enhancement', 'Enhancement'), ('Feature Request', 'Feature Request'), ('Bug', 'Bug'), ('Documentation', 'Documentation'), ('Design', 'Design')], default='User Story', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
