# Generated by Django 5.1.3 on 2025-01-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_tasks_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='done',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='description',
            new_name='items',
        ),
    ]
