# Generated by Django 5.1.3 on 2025-01-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_rename_done_subtask_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='board',
            field=models.CharField(choices=[('toDo', 'toDo'), ('inProgress', 'inProgress'), ('awaitFeedback', 'awaitFeedback'), ('done', 'done')], default='toDo', max_length=50),
        ),
    ]
