# Generated by Django 5.1.3 on 2025-01-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_tasks_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='board',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='subtasks',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='updated_at',
        ),
    ]
