# Generated by Django 5.1.3 on 2025-11-09 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_tasks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
