# Generated by Django 5.1.3 on 2025-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='board',
            field=models.CharField(choices=[('toDo', 'toDo'), ('inProgress', 'inProgress'), ('awaitFeedback', 'awaitFeedback'), ('done', 'done')], default='toDo', max_length=50),
        ),
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('User Story', 'User Story'), ('Testing', 'Testing'), ('Research', 'Research'), ('Other', 'Other'), ('Technical Task', 'Technical Task'), ('Infrastructure', 'Infrastructure'), ('Enhancement', 'Enhancement'), ('Feature Request', 'Feature Request'), ('Bug', 'Bug'), ('Documentation', 'Documentation'), ('Design', 'Design')], default='User Story', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
    ]
