# Generated by Django 5.1.3 on 2025-11-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_tasks_board_tasks_category_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('User Story', 'User Story'), ('Testing', 'Testing'), ('Research', 'Research'), ('Other', 'Other'), ('Technical Task', 'Technical Task'), ('Infrastructure', 'Infrastructure'), ('Enhancement', 'Enhancement'), ('Feature Request', 'Feature Request'), ('Bug', 'Bug'), ('Documentation', 'Documentation'), ('Design', 'Design')], default='User Story', max_length=255),
        ),
    ]
